name: Angular start

on:
  push:
    paths:
      - 'angular-start/**'
      - '.github/workflows/angular-start.yml'

jobs:
  mongodb-action:
    runs-on: ubuntu-latest

    name: Start Node
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install
        working-directory: ./angular-start
        env:
          CI: true

      # Fix 'Unable to open X display.'
      # https://remarkablemark.org/blog/2020/12/12/headless-test-in-github-actions-workflow/
      - run: sudo apt-get install xvfb

      - run: xvfb-run --auto-servernum  npm run test
        working-directory: ./angular-start
        env:
          CI: true